# Generated by Django 5.0.3 on 2024-03-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('street', models.CharField()),
                ('zipcode', models.BigIntegerField()),
                ('state', models.CharField()),
                ('appt_num', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('account_type', models.CharField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('middle_init', models.CharField(default=None)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('number_of_employees', models.BigIntegerField()),
                ('rating', models.FloatField()),
                ('owner', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField()),
                ('in_stock', models.BigIntegerField()),
                ('rating', models.CharField()),
            ],
        ),
    ]
