# Generated by Django 5.0.3 on 2024-03-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_store_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='appt_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
